// Renders the sample data set as supabase/seed.sql. Run `npm run db:seed:generate`
// after changing sample.ts; a unit test fails if the file is out of date.

import {
  activityToRow,
  commentToRow,
  contractToRow,
  dailyChangeToRow,
  languageToRow,
  profileToRow,
  versionToRow,
} from "./rows";
import type { SampleDataset } from "./sample";

type ColumnKind = "value" | "jsonb" | "text[]";

function literal(value: unknown, kind: ColumnKind): string {
  if (value === null || value === undefined) return "null";
  if (kind === "jsonb") return `${quote(JSON.stringify(value))}::jsonb`;
  if (kind === "text[]") {
    const items = value as string[];
    return items.length === 0 ? "'{}'::text[]" : `array[${items.map(quote).join(", ")}]::text[]`;
  }
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") return String(value);
  return quote(String(value));
}

function quote(text: string): string {
  return `'${text.replace(/'/g, "''")}'`;
}

function insert(table: string, rows: Record<string, unknown>[], kinds: Record<string, ColumnKind> = {}): string {
  if (rows.length === 0) return `-- ${table}: no rows\n`;
  const columns = Object.keys(rows[0]);
  const values = rows
    .map((row) => `  (${columns.map((c) => literal(row[c], kinds[c] ?? "value")).join(", ")})`)
    .join(",\n");
  return `insert into public.${table} (${columns.join(", ")}) values\n${values};\n`;
}

const VERSION_KINDS: Record<string, ColumnKind> = {
  skills: "text[]",
  portfolio: "jsonb",
  project_catalog: "jsonb",
  certifications: "jsonb",
  employment_history: "jsonb",
  other_experiences: "jsonb",
};

export function renderSeedSql(data: SampleDataset): string {
  const withoutActor = <T extends { actor_id?: unknown }>(row: T) => {
    const { actor_id: _actor, ...rest } = row;
    void _actor;
    return rest;
  };

  return [
    "-- Sample data for local development and demos.",
    "-- GENERATED by scripts/generate-seed.ts from src/lib/data/sample.ts. Do not edit by hand.",
    "--",
    "-- Log triggers are switched off while seeding: the historical activity rows below",
    "-- are inserted explicitly (negative tx ids never collide with real transactions).",
    "",
    "select set_config('app.skip_log', 'on', false);",
    "",
    insert("profiles", data.profiles.map(profileToRow), { categories: "text[]" }),
    insert("profile_languages", data.languages.map(languageToRow)),
    insert("profile_versions", data.versions.map(versionToRow), VERSION_KINDS),
    insert("daily_changes", data.dailyChanges.map(dailyChangeToRow), { old_value: "jsonb", new_value: "jsonb" }),
    insert("contracts", data.contracts.map((c) => contractToRow(c, c.deletedAt))),
    insert("contract_comments", data.comments.map((c) => withoutActor(commentToRow(c)))),
    insert("activity_log", data.activity.map((a) => withoutActor(activityToRow(a))), { details: "jsonb" }),
    "select set_config('app.skip_log', '', false);",
    "",
  ].join("\n");
}
